### ISSUE TITLE
Unhandled promise rejection,  duplicate key error collection: twitfeeder1.posts

### ISSUE THREAD

**Issue by handankel** [AKindley/manaiakalani-blogsheets-app#1]
`(node:3668) UnhandledPromiseRejectionWarning: BulkWriteError: E11000 duplicate key error collection: twitfeeder1.posts index: url_1 dup key: { url: "https://noahsfoa.blogspot.com/2019/10/term-4-maths-goals.html" }
    at OrderedBulkOperation.handleWriteError (/var/www/manaiakalani-blogsheets-app/node_modules/mongodb/lib/bulk/common.js:1112:11)
    at resultHandler (/var/www/manaiakalani-blogsheets-app/node_modules/mongodb/lib/bulk/common.js:501:23)
    at /var/www/manaiakalani-blogsheets-app/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:3668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1500)`

**Comment by handankel** [comment]
This is now resolved.  It adds an error record to the sheet as Bad url
